apiVersion: contoso.com/v1alpha1
kind: MyPlatform
metadata:
  name: test-dotnet-app
spec:
  appId: testdotnetapp
  language: rust # Invalid value
  os: linux
  instanceSize: small
  environmentType: dev
  replicas: 3
